[package]
name = "gameboy-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfields = "1.0.0"
bitflags = "2.9.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
